version: "3.4"

services:
  gunicorn-spawn:
    image: gunicorn-spawn
    restart: always
    build:
      context: .
      dockerfile: ./dockerfile
      target: GUNICORN_FAST_API

    ports: 
     - 82:80